# Generated by Django 3.0.4 on 2020-07-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=7),
        ),
    ]
