# Generated by Django 3.0.4 on 2020-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default='private', max_length=10),
        ),
    ]
