# Generated by Django 3.0.4 on 2020-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200713_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='private',
        ),
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
