# Generated by Django 3.0.4 on 2020-07-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200714_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
    ]
