# Generated by Django 3.0.4 on 2020-07-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
