# Generated by Django 3.0.4 on 2020-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200713_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='postype',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default='private', max_length=100),
        ),
    ]
