# Generated by Django 3.0.4 on 2020-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200713_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postype',
            field=models.CharField(max_length=100),
        ),
    ]
