# Generated by Django 3.0.4 on 2020-07-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200713_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='color',
        ),
    ]
