# Generated by Django 3.0.4 on 2020-07-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200714_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='public',
            new_name='box',
        ),
    ]
