# Generated by Django 3.0.4 on 2020-07-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200714_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='box',
            new_name='public',
        ),
    ]
