# Generated by Django 3.0.4 on 2020-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
